version: '3'

services:
  turbo-cache:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - turbo-cache-data:/app/cache
    environment:
      - TURBO_TOKEN=your-secret-token
      - STORAGE_PROVIDER=fs
      - STORAGE_PATH=/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  turbo-cache-data: 