version: '3.8'

services:
  cache-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - cache-data:/app/cache
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - TURBO_TOKEN=${TURBO_TOKEN}
      - ALLOWED_TEAMS=${ALLOWED_TEAMS}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  cache-data: 