name: Build with Custom Remote Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_API: ${{ secrets.TURBO_CACHE_SERVER_URL }}

jobs:
  setup-cache-server:
    runs-on: ubuntu-latest
    services:
      turbo-cache:
        image: node:18-alpine
        ports:
          - 3000:3000
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          STORAGE_PROVIDER: fs
          STORAGE_PATH: /app/cache
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 3
          --health-start-period 10s

  build:
    needs: setup-cache-server
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.STORE_PATH }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup Turbo cache
        uses: actions/cache@v3
        with:
          path: |
            .turbo
            **/.turbo
          key: turbo-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-

      - name: Clean node_modules
        run: |
          rm -rf node_modules
          rm -rf apps/*/node_modules
          rm -rf packages/*/node_modules

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check Remote Cache Status
        run: |
          echo "Checking remote cache status before build..."
          pnpm exec turbo build --dry --summarize

      - name: Build
        run: pnpm exec turbo build --summarize
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_API: http://localhost:3000

      - name: Verify Cache Status
        if: always()
        run: |
          echo "Verifying cache status after build..."
          pnpm exec turbo build --dry --summarize 